os:
  osx
language: java

before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

install: true
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.cache

script:  
  - mvn clean
  - mvn install
